name: 15-minute-cron
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: detect malicious content including phone numbers
        run: |
          curl --request POST \
          --url 'https://nextapp1-ivory.com/api/cron'
